services:
  sdk:
    image: openwrtorg/sdk:x86_64-openwrt-22.03
    volumes:
      - .:/home/build/openwrt/mosdns/mosdns
      - ./bin:/home/build/openwrt/bin
      - ./build.sh:/home/build/openwrt/build.sh
    command: /home/build/openwrt/build.sh
      